#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64  "ak----/0-----311@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF



  CREATE TABLE "ASSIGNED_NURSE"
   ( "NURSEID" VARCHAR2(20 BYTE),
"TYPEOFNURSE" VARCHAR2(20 BYTE),
"EMPLOYEEID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;


  CREATE TABLE "COVERAGE_DETAILS"
   ( "COVERAGEID" VARCHAR2(20 BYTE),
"COVERAGETYPE" VARCHAR2(35 BYTE),
"COPAYAMOUNT" NUMBER(10,2),
"POLICYINCLUSIONSTATUS" VARCHAR2(30 BYTE),
"INSURANCENUMBER" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;


  CREATE TABLE "DOCTOR"
   ( "DOCTORID" VARCHAR2(20 BYTE),
"SPECIALTY" VARCHAR2(35 BYTE),
"EMPLOYEEID" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;


  CREATE TABLE "EMERGENCY_CONTACTS"
   ( "NAME" VARCHAR2(35 BYTE),
"ADDRESS" VARCHAR2(40 BYTE),
"PHONENUMBER" VARCHAR2(35 BYTE),
"HEALTHCARDNUMBER" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;


  CREATE TABLE "HEALTH_RECORD"
   ( "HEALTHRECORDID" VARCHAR2(15 BYTE),
"ORGANDONOR" VARCHAR2( 5 BYTE),
"HEALTHCARDNUMBER" VARCHAR2(15 BYTE),
"VITALINFO" VARCHAR2(29 BYTE),
"IMMUNIZATIONRECORD" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;


  CREATE TABLE "HOSPITAL"
   ( "HOSPITALID" VARCHAR2(20 BYTE),
"NAME" VARCHAR2(24 BYTE),
"CITY" VARCHAR2(100 BYTE),
"STREET" VARCHAR2(35 BYTE),
"POSTALCODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;


  CREATE TABLE "INSURANCE"
   ( "INSURANCENUMBER" VARCHAR2(20 BYTE),
"INSURANCEPROVIDER" VARCHAR2(25 BYTE),
"HEALTHCARDNUMBER" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;

  CREATE TABLE "MAINTENANCE"
   ( "MAINTENANCEID" VARCHAR2(25 BYTE),
"WARDOFRESPONSIBILITY" VARCHAR2(25 BYTE),
"EMPLOYEEID" VARCHAR2(25 BYTE),
"OCCUPATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;


  CREATE TABLE "MEDICATIONS"
   ( "MEDICATIONID" VARCHAR2(25 BYTE),
"DOSAGE" VARCHAR2(20 BYTE),
"BRAND" VARCHAR2(100 BYTE),
"SIDEEFFECTS" VARCHAR2(20 BYTE),
"HEALTHRECORDID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;

  CREATE TABLE "OPERATIONS"
   ( "SURGERYID" VARCHAR2(25 BYTE),
"SURGERYNAME" VARCHAR2(25 BYTE),
"SURGEONNAME" VARCHAR2(25 BYTE),
"HEALTHRECORDID" VARCHAR2(25 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;

  CREATE TABLE "PATIENT"
   ( "FIRSTNAME" VARCHAR2(20 BYTE),
"LASTNAME" VARCHAR2(20 BYTE),
"HEALTHCARDNUMBER" VARCHAR2(15 BYTE),
"GENDER" VARCHAR2(6 BYTE),
"DATEOFBIRTH" DATE,
"AGE" NUMBER(*,0),
"HOSPITALID" VARCHAR2( 20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;


  CREATE TABLE "STAFF"
   ( "EMPLOYEEID" VARCHAR2(20 BYTE),
"DEPARTMENT" VARCHAR2(20 BYTE),
"HOSPITALID" VARCHAR2(20 BYTE),
"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;



exit;
EOF
