#!/bin/sh

sqlplus64  "ak----/0-----31@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<END_SCRIPT

DROP TABLE EMERGENCY_CONTACTS CASCADE CONSTRAINTS;
DROP TABLE COVERAGE_DETAILS CASCADE CONSTRAINTS;
DROP TABLE INSURANCE CASCADE CONSTRAINTS;
DROP TABLE MEDICATIONS CASCADE CONSTRAINTS;
DROP TABLE OPERATIONS CASCADE CONSTRAINTS;
DROP TABLE MAINTENANCE CASCADE CONSTRAINTS;
DROP TABLE DOCTOR CASCADE CONSTRAINTS;
DROP TABLE ASSIGNED_NURSE CASCADE CONSTRAINTS;
DROP TABLE STAFF CASCADE CONSTRAINTS;
DROP TABLE HEALTH_RECORD CASCADE CONSTRAINTS;
DROP TABLE PATIENT CASCADE CONSTRAINTS;
DROP TABLE HOSPITAL CASCADE CONSTRAINTS;

exit;
END_SCRIPT
