REM INSERTING into AKIBRIA.ASSIGNED_NURSE
SET DEFINE OFF;
Insert into AKIBRIA.ASSIGNED_NURSE (NURSEID,TYPEOFNURSE,EMPLOYEEID) values ('NRS001','ICU Nurse','EMP006');
Insert into AKIBRIA.ASSIGNED_NURSE (NURSEID,TYPEOFNURSE,EMPLOYEEID) values ('NRS002','Pediatric Nurse','EMP007');
Insert into AKIBRIA.ASSIGNED_NURSE (NURSEID,TYPEOFNURSE,EMPLOYEEID) values ('NRS003','Operating Room Nurse','EMP008');
Insert into AKIBRIA.ASSIGNED_NURSE (NURSEID,TYPEOFNURSE,EMPLOYEEID) values ('NRS004','Emergency Room Nurse','EMP009');
Insert into AKIBRIA.ASSIGNED_NURSE (NURSEID,TYPEOFNURSE,EMPLOYEEID) values ('NRS005','Gynocology Nurse','EMP010');
Insert into AKIBRIA.ASSIGNED_NURSE (NURSEID,TYPEOFNURSE,EMPLOYEEID) values ('NR006','Gynocology Nurse','EMP016');
