REM INSERTING into AKIBRIA.DOCTOR
SET DEFINE OFF;
Insert into AKIBRIA.DOCTOR (DOCTORID,SPECIALTY,EMPLOYEEID) values ('DOC001','Cardiology ','EMP001');
Insert into AKIBRIA.DOCTOR (DOCTORID,SPECIALTY,EMPLOYEEID) values ('DOC002','Orthopedics','EMP002');
Insert into AKIBRIA.DOCTOR (DOCTORID,SPECIALTY,EMPLOYEEID) values ('DOC003','neurology ','EMP003');
Insert into AKIBRIA.DOCTOR (DOCTORID,SPECIALTY,EMPLOYEEID) values ('DOC004','General','EMP004');
Insert into AKIBRIA.DOCTOR (DOCTORID,SPECIALTY,EMPLOYEEID) values ('DOC005','General','EMP005');
