--------------------------------------------------------
--  File created - Friday-November-03-2023   
--------------------------------------------------------
@C:\Users\1kibr\Downloads\ASSIGNED_NURSE.sql
@C:\Users\1kibr\Downloads\COVERAGE_DETAILS.sql
@C:\Users\1kibr\Downloads\DOCTOR.sql
@C:\Users\1kibr\Downloads\EMERGENCY_CONTACTS.sql
@C:\Users\1kibr\Downloads\HEALTH_RECORD.sql
@C:\Users\1kibr\Downloads\HOSPITAL.sql
@C:\Users\1kibr\Downloads\INSURANCE.sql
@C:\Users\1kibr\Downloads\MAINTENANCE.sql
@C:\Users\1kibr\Downloads\MEDICATIONS.sql
@C:\Users\1kibr\Downloads\OPERATIONS.sql
@C:\Users\1kibr\Downloads\PATIENT.sql
@C:\Users\1kibr\Downloads\STAFF.sql
@C:\Users\1kibr\Downloads\HOSPITALSTAFFMAINTENANCE.sql
@C:\Users\1kibr\Downloads\PATIENTHEALTHRECORDS.sql
@C:\Users\1kibr\Downloads\PATIENTMEDICATIONCOUNT.sql
@C:\Users\1kibr\Downloads\PATIENTSWITHOUTSURGERIES.sql
@C:\Users\1kibr\Downloads\ASSIGNED_NURSE_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\COVERAGE_DETAILS_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\DOCTOR_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\EMERGENCY_CONTACTS_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\HEALTH_RECORD_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\HOSPITAL_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\INSURANCE_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\MAINTENANCE_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\MEDICATIONS_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\OPERATIONS_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\PATIENT_DATA_TABLE.sql
@C:\Users\1kibr\Downloads\STAFF_DATA_TABLE.sql
