--------------------------------------------------------
--  DDL for Table HEALTH_RECORD
--------------------------------------------------------

  CREATE TABLE "AKIBRIA"."HEALTH_RECORD" 
   (	"HEALTHRECORDID" VARCHAR2(15 BYTE), 
	"ORGANDONOR" VARCHAR2(5 BYTE), 
	"HEALTHCARDNUMBER" VARCHAR2(15 BYTE), 
	"VITALINFO" VARCHAR2(29 BYTE), 
	"IMMUNIZATIONRECORD" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
