REM INSERTING into AKIBRIA.HOSPITAL
SET DEFINE OFF;
Insert into AKIBRIA.HOSPITAL (HOSPITALID,NAME,CITY,STREET,POSTALCODE) values ('B2C3E4g5','Toronto General Hospital','Toronto','200 Elizabeth St','M5G 2C4');
