REM INSERTING into AKIBRIA.MAINTENANCE
SET DEFINE OFF;
Insert into AKIBRIA.MAINTENANCE (MAINTENANCEID,WARDOFRESPONSIBILITY,EMPLOYEEID,OCCUPATION) values ('MTN001','Ward A','EMP011','Technician');
Insert into AKIBRIA.MAINTENANCE (MAINTENANCEID,WARDOFRESPONSIBILITY,EMPLOYEEID,OCCUPATION) values ('MTN002','Ward B','EMP012','Janitor');
Insert into AKIBRIA.MAINTENANCE (MAINTENANCEID,WARDOFRESPONSIBILITY,EMPLOYEEID,OCCUPATION) values ('MTN003','Ward C','EMP013','Plumber');
Insert into AKIBRIA.MAINTENANCE (MAINTENANCEID,WARDOFRESPONSIBILITY,EMPLOYEEID,OCCUPATION) values ('MTN004','Ward D','EMP014','Electrician');
Insert into AKIBRIA.MAINTENANCE (MAINTENANCEID,WARDOFRESPONSIBILITY,EMPLOYEEID,OCCUPATION) values ('MTN005','Ward E','EMP015','Electrician');
Insert into AKIBRIA.MAINTENANCE (MAINTENANCEID,WARDOFRESPONSIBILITY,EMPLOYEEID,OCCUPATION) values ('MTH006','Ward E','EMP017','Janitor');
