--------------------------------------------------------
--  DDL for Table MEDICATIONS
--------------------------------------------------------

  CREATE TABLE "AKIBRIA"."MEDICATIONS" 
   (	"MEDICATIONID" VARCHAR2(25 BYTE), 
	"DOSAGE" VARCHAR2(20 BYTE), 
	"BRAND" VARCHAR2(100 BYTE), 
	"SIDEEFFECTS" VARCHAR2(20 BYTE), 
	"HEALTHRECORDID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DBCOURSE" ;
