REM INSERTING into AKIBRIA.OPERATIONS
SET DEFINE OFF;
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP111','Tumor Resection','Michael Smith','HR6969697');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP222','Knee Replacement','Jane Johnson','HR3456780');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP333','Heart Transplant','John Brown','HR6789011');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP444','Colectomy ','Emily Williams','HR9012342');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP555','Gastric Bypass Surgery','Michael Smith','HR5678903');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP666','Hip Replacement','Jane Johnson','HR2345674');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP777','Coronary Bypass','John Brown','HR8901235');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP888','Hernia Repair','Emily Williams','HR4567896');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP999','Craniotomy','Michael Smith','HR0123457');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP101010','Rotator Cuff Repair','Jane Johnson','HR6789018');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP121212','Angioplasty ','John Brown','HR123456');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP131313','Appendectomy ','Emily Williams','HR789012');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP141414','Laminectomy','Michael Smith','HR345678');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP151515','Lumbar Fusion','Jane Johnson','HR901234');
Insert into AKIBRIA.OPERATIONS (SURGERYID,SURGERYNAME,SURGEONNAME,HEALTHRECORDID) values ('OP161616','Pacemaker Implantation','John Brown','HR567890');
