--------------------------------------------------------
--  DDL for View PATIENTMEDICATIONCOUNT
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "AKIBRIA"."PATIENTMEDICATIONCOUNT" ("FIRSTNAME", "LASTNAME", "HEALTHCARDNUMBER", "MEDICATIONCOUNT") AS 
  SELECT p.FIRSTNAME, p.LASTNAME, p.HEALTHCARDNUMBER, COUNT(m.MEDICATIONID) AS MedicationCount
FROM PATIENT p
LEFT JOIN HEALTH_RECORD h ON p.HEALTHCARDNUMBER = h.HEALTHCARDNUMBER
LEFT JOIN MEDICATIONS m ON h.HEALTHRECORDID = m.HEALTHRECORDID
GROUP BY p.FIRSTNAME, p.LASTNAME, p.HEALTHCARDNUMBER
;
