--------------------------------------------------------
--  DDL for View PATIENTSWITHOUTSURGERIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "AKIBRIA"."PATIENTSWITHOUTSURGERIES" ("FIRSTNAME", "LASTNAME") AS 
  SELECT p.FIRSTNAME, p.LASTNAME
FROM PATIENT p
LEFT JOIN HEALTH_RECORD h ON p.HEALTHCARDNUMBER = h.HEALTHCARDNUMBER
LEFT JOIN OPERATIONS o ON h.HEALTHRECORDID = o.HEALTHRECORDID
WHERE o.SURGERYID IS NULL
;
