REM INSERTING into AKIBRIA.STAFF
SET DEFINE OFF;
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP001','Doctor','B2C3E4g5','John Brown');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP002','Doctor','B2C3E4g5','Jane Johnson');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP003','Doctor','B2C3E4g5','Michael Smith');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP004','Doctor','B2C3E4g5','Emily Williams');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP005','Doctor','B2C3E4g5','James Davis');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP006','Nurse','B2C3E4g5','Aisha Patel');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP007','Nurse','B2C3E4g5','David Taylor');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP008','Nurse','B2C3E4g5','Priya Gupta');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP009','Nurse','B2C3E4g5','Daniel Wilson');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP010','Nurse','B2C3E4g5','Mei Chen');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP011','Maintenance','B2C3E4g5','John Doe');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP012','Maintenance','B2C3E4g5','Jane Smith');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP013','Maintenance','B2C3E4g5','Michael Johnson');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP014','Maintenance','B2C3E4g5','Emily Davis');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP015','Maintenance','B2C3E4g5','James Wilson');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP016','Nurse','B2C3E4g5','Kartike khan');
Insert into AKIBRIA.STAFF (EMPLOYEEID,DEPARTMENT,HOSPITALID,NAME) values ('EMP017','Maintenance','B2C3E4g5','Raza Khan');
